# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of image'
        type: string
        default: 'latest'
        required: true

jobs:
  build_package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt-hotspot'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - name: Upload JAR-file
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: ./target/*.jar

  build_image_and_push_to_dockerhub:
    needs: [ build_package ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download JAR-file
        uses: actions/download-artifact@v3
        with:
          name: package
          path: ./target
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag antey1988/money-transfer:${{ github.event.inputs.tag }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Docker image
        run: docker push antey1988/money-transfer:${{ github.event.inputs.tag }}